AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  zip

  Sample SAM Template for zip

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 29
    MemorySize: 1024

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: com.example.spring_public_postgres.LambdaHandler::handleRequest
      Runtime: java21
#If you deploy the Spring Boot(Lambdas) in a Custom VPC(With VpcConfig section below) you will need a VPCEndpoint for Secret Manager
#If you don't have a VPC Endpoint to access Secrets Manager in a Custom VPC you will get a timeout when trying to retrieve the secret
#If you deploy your Spring Boot(Lambdas) into the default VPC(Without VpcConfig section below) you do not need a VPC Endpoint for Secret Manager
# VpcConfig section Required for Deployment in Custom VPC
      VpcConfig:
        SecurityGroupIds:
          - sg-0eb14a26be232facf
        SubnetIds:
          - subnet-0aaeb33bf4c66039f
          - subnet-0def4bd6cd6345ab5
          - subnet-0c4f8370b831ead59
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:RDSdevdbsecret-q2h3qu"
      Architectures:
        - x86_64
      MemorySize: 1024
      SnapStart:
        ApplyOn: "PublishedVersions"      
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/test/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
